### ISSUE TITLE
A javascript error occurred in the main process

### ISSUE THREAD

**Issue by beebase** [vuetwo/vuetron#85]
I'm getting these errors in the Vuetron app
![img2635](https://user-images.githubusercontent.com/446089/33477558-5c8ee30e-d686-11e7-8514-d8472ab3e686.jpg)
 (OSX)
```
Uncaught Exception:
TypeError: Cannot read property 'lhs' of undefined
    at deepDiff (/Applications/Vuetron.app/Contents/Resources/app/vuetron-server/node_modules/deep-diff/index.js:156:76)
    at accumulateDiff (/Applications/Vuetron.app/Contents/Resources/app/vuetron-server/node_modules/deep-diff/index.js:213:3)
    at Socket.<anonymous> (/Applications/Vuetron.app/Contents/Resources/app/vuetron-server/lib/sockets.js:41:21)
    at emitTwo (events.js:106:13)
    at Socket.emit (events.js:194:7)
    at /Applications/Vuetron.app/Contents/Resources/app/vuetron-server/node_modules/socket.io/lib/socket.js:513:12
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)
```

**Comment by samanthasalley** [comment]
Hi @beebase, that error occurs when Vuetron does not have a current application state to parse the differences and is usually caused if you've opened your application _before_ starting Vuetron and do not refresh your application before making changes.  

To fix this, once you've opened both Vuetron and your application, try refreshing your application and make sure you see the 'Connected to App' and 'State Initialized' (if using Vuex) events in the event stream.

If you are still seeing this error please let us know!

**Comment by beebase** [comment]
restarting all, fixed it. thanks.
